<?php
$translate = $this->plugin('translate');
$searchType = $this->siteSetting('search_type', 'sitewide');
switch ($searchType) {
    case 'cross-site':
        $searchAction = $this->url('site/cross-site-search', ['action' => 'results'], true);
        break;
    case 'sitewide':
    default:
		$searchAction = $site->url().'/search';
}
$searchValue = $this->escapeHtml($this->params()->fromQuery('q', ''));
?>

<form action="<?php echo $this->escapeHtml($searchAction); ?>" id="search-form">
    <input type="text" name="q" value="<?php echo $searchValue; ?>"
        placeholder="<?php echo $translate('Search'); ?>"
        aria-label="<?php echo $translate('Search'); ?>">
    <button type="submit"><i class="fa fa-search"></i><span class="screen-reader-text"><?php echo $translate('Search'); ?></span></button>
</form>
<div class="button-container">
    <a href="<?php echo $site->url(); ?>/search" class="button button--advanced"><i class="fas fa-plus-circle"></i><?php echo $translate('Advanced search'); ?></a>
</div>
