<?php
$translate = $this->plugin('translate');
$prevText = $translate('Prev');
$nextText = $translate('Next');
?>
<?php if ($prevPage || $nextPage): ?>
<div class="site-page-pagination wrap wrap--xl">
	<div class="wrap wrap--lg">
		<?php echo $prevPage ? '<span class="page__prev">'.$this->hyperlink($prevText, $prevPage->siteUrl()).'</span>' : ''; ?>
		<?php echo $nextPage ? '<span class="page__next">'.$this->hyperlink($nextText, $nextPage->siteUrl()).'</span>' : ''; ?>
	</div>
</div>
<?php endif; ?>