<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

$user = $this->identity();


// Item metadata for search link
$itemdataSearchSelection = $this->themeSetting( 'itemdata_search' , '' );

// Regions
$section1BlockContent = $this->resourcePageBlocks($item, 'section1');
$section1HasBlocks = $section1BlockContent->hasBlocks();
$section2BlockContent = $this->resourcePageBlocks($item, 'section2');
$section2HasBlocks = $section2BlockContent->hasBlocks();
$mainBlockContent = $this->resourcePageBlocks($item);
$mainHasBlocks = $mainBlockContent->hasBlocks();

$itemDataDisplayOptions = [
    'showValueAnnotations' => true,
    'propertiesForSearch' => $itemdataSearchSelection,
    'multiValuesSeparator' => '<br/>'
];

$itemdataSection1HTML = '';
if ($itemdataSection1 = $this->themeSetting( 'itemdata_section1' )) {
    $itemdataSection1HTML = $this->DisplaySelectedValues($item, $itemdataSection1, $itemDataDisplayOptions );
}

$itemdataSection2HTML = '';
if ($itemdataSection2 = $this->themeSetting( 'itemdata_section2' )) {
    $itemdataSection2HTML = $this->DisplaySelectedValues($item, $itemdataSection2, $itemDataDisplayOptions );
}


?>

<?php
// Breadcrumb with Item Sets Tree
$itemSets = $item->itemSets(); 
$itemSetIds = array();
$counter = 0;
if (count($itemSets) > 0):
    foreach ($itemSets as $itemSet):
        if ($counter++ == 0):
            $itemSetIds[] = $itemSet->ID();
            $breadcrumbParents = '';
            $itemSetAncestors = array_reverse( $this->itemSetsTree()->getAncestors($itemSet) );
            foreach ( $itemSetAncestors as $ancestorItemSet):
                $breadcrumbParents .= '&gt; '.$ancestorItemSet->link($ancestorItemSet->displayTitle()).' ';
            endforeach;
            ?>
            <nav class="breadcrumbs wrap wrap--lg"><a href="<?php echo $this->url('site', [], [], true); ?>"><?php echo $translate('Home'); ?></a> <?php echo $breadcrumbParents; ?> &gt; <a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a> &gt; <span><?php echo $item->displayTitle(); ?></span></nav>
            <?php
        endif;
    endforeach;
endif;
?>
<div class="blocks">
    <?php if ($this->getHelperPluginManager()->has('shareMeBaby')) : ?>
        <div class="block-share-me-baby"><div class="wrap wrap--lg"><?php echo $this->shareMeBaby(); ?></div></div>
    <?php endif; ?>
    <div class="page-title"><?php echo $this->pageTitle($item->displayTitle(null, $valueLang), 1); ?></div>
    <div class="wrap wrap--xl">

        <?php $this->trigger('view.show.before'); ?>

        <?php if ($mainHasBlocks || $section1HasBlocks || $section2HasBlocks || $itemdataSection1HTML || $itemdataSection2HTML): ?>

            <?php
            $sectionsContainerClasses = '';
            if ( ($section1HasBlocks && $section2HasBlocks) || ($itemdataSection1HTML && $itemdataSection2HTML) ) {
                $sectionsContainerClasses = 'two-sections';
            } elseif ( $section1HasBlocks || $section2HasBlocks || $itemdataSection1HTML || $itemdataSection2HTML ) {
                $sectionsContainerClasses = 'one-section';
            }

            $displayMode = ($this->themeSetting('items_display_mode')) ?: 2;
            if ( $displayMode == 1 ) {
                $sectionsContainerClasses .= ' one-column';
            }

            ?>
            <div class="regions-container <?php echo $sectionsContainerClasses; ?>">
                <?php if ( ($section1HasBlocks && $blockContent = $section1BlockContent->getBlocks()) || $itemdataSection1HTML): ?>
                    <div class="region region--section section1">
                        <div class="metadata">
                            <?php echo $blockContent; ?>

                            <?php
                                // test medias acces restreint
                                $embedMedia = $this->siteSetting('item_media_embed', false);
                                $itemMedia = $item->media();

                                //echo ($itemMedia)? 'Dollar Item Media = '.$itemMedia.'<br>' : 'item Media est vide !!! <br>';

                                $access_img = $this->themeSetting('items_access_img');
                                $access_title = $this->themeSetting('items_access_title');
                                $access_text = $this->themeSetting('items_access_text');
                                $access_label = $this->themeSetting('items_access_label');
                                $access_url = $this->themeSetting('items_access_url');
                                $access_title_connected = $this->themeSetting('items_access_title_connected');
                                $access_text_connected = $this->themeSetting('items_access_text_connected');
                                $access_label_connected = $this->themeSetting('items_access_label_connected');
                                $access_url_connected = $this->themeSetting('items_access_url_connected');
                            ?>
                            <?php if (!($embedMedia || $itemMedia)) :  //echo "NO MEDIA"; ?>
                            
                            <div class="item-access">
                                <?php if($access_img): ?>
                                    <div class="item-access__thumbnail">
                                        <img src="<?php echo $this->themeSettingAssetUrl('items_access_img'); ?>">
                                    </div>
                                <?php endif; ?>

                                    <div class="item-access__content">
                                <?php if (isset($user)): ?>
                                        <p class="h2 item-access__title"><?php echo ($access_title_connected)? $access_title_connected : $translate('Document access'); ?></p>

                                        <?php echo ($access_text_connected)? '<div class="item-access__text">'.$access_text_connected.'</div>' : ''; ?>
                                        
                                        <?php if($access_label_connected && $access_url_connected ): 
                                            echo '<div class="button__container"><a href="'.$access_url_connected.'" class="button">'.$access_label_connected.'</a></div>';
                                        endif; ?>

                                <?php else: ?>
                                    <p class="h2 item-access__title"><?php echo ($access_title)? $access_title : $translate('Document access'); ?></p>

                                    <?php echo ($access_text)? '<div class="item-access__text">'.$access_text.'</div>' : ''; ?>

                                    <?php if($access_label && $access_url ): 
                                        echo '<div class="button__container"><a href="'.$access_url.'" class="button">'.$access_label.'</a></div>';
                                    endif; ?>

                                <?php endif; ?>

                                    </div>
                            </div>

                            <?php //else: echo "MEDIA OK"; ?>
                            <?php endif; ?>

                            <?php
                            // Affichage métadonnées section 1
                            echo ($itemdataSection1HTML) ? '<div class="properties-wrapper">'.$itemdataSection1HTML.'</div>' : '';
                            $blockContent = '';
                            ?>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="region region--section section1">
                        <div class="metadata">
                            <?php
                                // test medias acces restreint
                                $embedMedia = $this->siteSetting('item_media_embed', false);
                                $itemMedia = $item->media();

                                //echo ($itemMedia)? 'Dollar Item Media = '.$itemMedia.'<br>' : 'item Media est vide !!! <br>';

                                $access_title = $this->themeSetting('items_access_title');
                                $access_text = $this->themeSetting('items_access_text');
                                $access_label = $this->themeSetting('items_access_label');
                                $access_url = $this->themeSetting('items_access_url');
                                $access_title_connected = $this->themeSetting('items_access_title_connected');
                                $access_text_connected = $this->themeSetting('items_access_text_connected');
                            ?>
                            <?php if (!($embedMedia || $itemMedia)) :  //echo "NO MEDIA"; ?>
                            
                            <div class="item-access">
                                <?php if (isset($user)): ?>

                                    <p class="h2 item-access__title"><?php echo ($access_title_connected)? $access_title_connected : $translate('Document access'); ?></p>

                                    <?php echo ($access_text_connected)? '<div class="item-access__text">'.$access_text_connected.'</div>' : ''; ?>

                                <?php else: ?>
                                    <p class="h2 item-access__title"><?php echo ($access_title)? $access_title : $translate('Document access'); ?></p>

                                    <?php echo ($access_text)? '<div class="item-access__text">'.$access_text.'</div>' : ''; ?>

                                    <?php if($access_label && $access_url ): 
                                        echo '<div class="button__container"><a href="'.$access_url.'" class="button">'.$access_label.'</a></div>';
                                    endif; ?>

                                <?php endif; ?>
                            </div>

                            <?php //else: echo "MEDIA OK"; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif; ?>

                <?php if ( ($section2HasBlocks && $blockContent = $section2BlockContent->getBlocks()) || $itemdataSection2HTML): ?>
                    <div class="region region--section section2">
                        <div class="metadata">
                            <?php echo $blockContent; ?>
                            <?php
                            // Affichage métadonnées section 2
                            echo ($itemdataSection2HTML) ? '<div class="properties-wrapper">'.$itemdataSection2HTML.'</div>' : '';
                            $blockContent = '';
                            ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>

            <?php if ($mainHasBlocks && $blockContent = $mainBlockContent->getBlocks()): ?>
                <div class="main-region">
                    <div class="wrap wrap--md">
                        <div class="metadata">
                            <?php echo $blockContent; ?>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

        <?php endif; ?>
        <?php 

        $linkedItemsArray = $item->subjectValues();
        if($linkedItemsArray): 

            $itemdata_lists = $this->themeSetting( 'itemdata_lists' );
        ?>
        <!-- Affichage des items liés -->
        <div class="slider-items wrap wrap--lg" aria-labelledby="related-documents-heading">
            <div class="slider-items__wrap wrap wrap--md">

                <h2 class="slider-items__title" id="related-documents-heading"><?php echo $translate('Related resources'); ?></h2>

                <div class="slider-items__list slider splide" id="related-slider">

                    <div class="splide__arrows">
                        <button class="splide__arrow splide__arrow--prev">
                            <i class="fa fa-caret-left"></i><span class="screen-reader-text"><?php echo $translate('Previous'); ?></span>
                        </button>
                        <button class="splide__arrow splide__arrow--next">
                            <i class="fa fa-caret-right"></i><span class="screen-reader-text"><?php echo $translate('Next'); ?></span>
                        </button>
                    </div>

                    <div class="splide__track">
                        <div class="splide__list">
                
                            <?php foreach ($linkedItemsArray as $linkedItem): ?>
                                <?php foreach ($linkedItem as $valueItem):
                                    $relatedResource = $valueItem['val']->resource();
                                    ?>
                                    <div class="slider-item splide__slide">
                                        
                                        <div class="slider-item__contents">
                                            <div class="slider-item__thumbnail">
                                                <?php echo $this->thumbnail($relatedResource, 'large', ['class' => 'media-thumbnail', 'title' => $relatedResource->displayTitle()]); ?>
                                            </div>
                                            <div class="slider-item__texts">
                                                <h3 class="slider-item__title">
                                                    <a href="<?php echo $relatedResource->url(); ?>" class="slider-item__link"><?php echo $relatedResource->displayTitle(); ?></a>
                                                </h3>                                           
                                                <div class="resource__metadatas">
                                                <?php
                                                $metadataContent = $this->DisplaySelectedValues($relatedResource, $itemdata_lists, [ 'stripTags' => true ] );
                                                if ($metadataContent) {
                                                    echo $metadataContent;
                                                }
                                                ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div><!-- .splide__slide -->
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </div><!-- .splide-list -->
                    </div><!-- .splide_track -->
                </div><!-- .slider -->
            </div>

        </div><!-- .wrap -->
        <script>
        document.addEventListener( 'DOMContentLoaded', function () {
            var splide = new Splide( '#related-slider', {
                arrows: true,
                keyboard: true,
                pagination: true,
                perPage: 3,
                breakpoints: {
                    1079: { perPage: 2, },
                    599 : { perPage: 1, }
                }
            } );

            // reference https://splidejs.com/guides/overflow/#loop-carousel
            splide.on( 'overflow', function ( isOverflow ) {
                splide.options = {
                    arrows    : isOverflow,
                    pagination: isOverflow,
                    drag      : isOverflow,
                };
            } );

            splide.mount();
        } );
        </script>

        <?php endif; ?>

        <?php $this->trigger('view.show.after'); ?>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
    $('body .regions-container a').each(function() {
        var href = $(this).attr('href');
        // Vérifie si le lien commence par http ou https et s'il ne provient pas du même domaine
        if (href && href.indexOf('http') === 0 && this.hostname !== window.location.hostname) {
            $(this).attr('target', '_blank'); // Ajoute target="_blank"
            $(this).attr('title', '<?php echo $translate('Open new tab'); ?>'); // Ajoute un titre
            $(this).append('<i class="fas fa-external-link-square-alt"></i>'); // Ajoute l'icône après le libellé du lien
        }
    });
    $('body .regions-container a.resource-link').each(function() {
        var href = $(this).attr('href');
        if (this.hostname == window.location.hostname) {
            $(this).find('img').remove(); // Supprime les images
            $(this).append('<i class="o-icon-uri"></i>'); // Ajoute l'icône après le libellé du lien
        }
    });


});
</script>