<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$escAttr = $this->plugin('escapeHtmlAttr');

$siteTitle = $site->title();

$footer_menu = $this->themeSetting('footer_menu');
$footer_copyright = $this->themeSetting('copyright');
$footer_logo2 = $this->themeSetting('logo_bis');
$footer_logo2_label = $this->themeSetting('logo_bis_label');
$footer_logo2_url = $this->themeSetting('logo_bis_url');

$socialNetworks  = array( 'facebook', 'bluesky', 'linkedin', 'instagram', 'youtube', 'vimeo', 'mastodon', 'x' );
$hasSocialNetworks = false;

foreach ( $socialNetworks as $social_network ) {
	if ( $this->themeSetting( "{$social_network}_url" ) ) {
		$hasSocialNetworks = true;
		break;
	}
}

?>
<?php if( $this->themeSetting( 'partners_show') == 1 ):

	$partners_title = $this->themeSetting('partners_title');
	$partners_label = $this->themeSetting('partners_label');
	$partners_url = $this->themeSetting('partners_url');

	$partnerImage = $this->themeSetting('partnerslist_logo1');
	$partnerLabel = $this->themeSetting('partnerslist_label1');

	$partners_allpages = $this->themeSetting('partners_show_allpages');
	$class_allpages = ' partners--onlyhome';
	if( $partners_allpages == 1 ): $class_allpages = ''; endif;

	if($partnerImage && $partnerLabel):
	?>
	<div class="footer-top partners<?php echo $class_allpages; ?>">
		<div class="wrap wrap--lg">
			<?php echo ($partners_title) ? '<p class="partners__title">'.$partners_title.'</p>' : ''; ?>
			<ul class="partners__list">
				<?php
				for($numPartner=1; $numPartner<=10; $numPartner++):
				
					$partner_image = $this->themeSetting('partnerslist_logo'.$numPartner);
					$partner_label = $this->themeSetting('partnerslist_label'.$numPartner);
					$partnerUrl = $this->themeSetting('partnerslist_url'.$numPartner);

					if ($partner_image && $partner_label):

						if($partnerUrl):
							$partner = '<a href="'.$partnerUrl.'" target="_blank" title="'.$partner_label.' - '.$translate('Open new tab').'"><img src="'.$this->themeSettingAssetUrl('partnerslist_logo'.$numPartner).'" alt="'.$partner_label.'"></a>';
						else:
							$partner = '<img src="'.$this->themeSettingAssetUrl('partnerslist_logo'.$numPartner).'" alt="'.$partner_label.'">';
						endif;
					?>
					<li class="partners__item">
						<?php echo $partner; ?>
					</li>

					<?php 	
					endif;
				endfor; 
				?>
			</ul>
				
			<?php echo ($partners_label && $partners_url) ? '<p class="partners__button"><a href="'.$partners_url.'" class="button">'.$partners_label.'</a></p>' : ''; ?>
		</div>
			
	</div>
	<?php endif; ?>
<?php endif; ?>

<footer class="footer">
	<div class="wrap wrap--lg">

		<?php 
			if ($footer_logo2 && $footer_logo2_label): 
				if($footer_logo2_url):
			?>
			<div class="footer__logo--bis">
				<a href="<?php echo $footer_logo2_url ?>">
					<img src="<?php echo $this->themeSettingAssetUrl('logo_bis'); ?>" alt="<?php echo $footer_logo2_label; ?>" />
				</a>
			</div>
				<?php else: ?>
			<div class="footer__logo--bis"><img src="<?php echo $this->themeSettingAssetUrl('logo_bis'); ?>" alt="<?php echo $footer_logo2_label; ?>" /></div>
			<?php endif; ?>
		<?php endif; ?>

		<?php if( $footer_menu ) : ?>
		<nav class="footer__nav">
			<?php echo $footer_menu; ?>
		</nav>
		<?php endif; ?>

		<!-- Social Networks -->
		<?php if ($hasSocialNetworks) : ?>
			<div class="footer__socials">
				<?php foreach ( $socialNetworks as $social_network ) : ?>
					<?php if ( $social_network_url = $this->themeSetting( "{$social_network}_url" ) ) : ?>
						<a href="<?php echo $social_network_url; ?>">
							<img src="<?php echo $this->assetUrl( "img/{$social_network}.svg" ); ?>"
								alt="<?php echo $escAttr( $social_network ); ?>">
						</a>
					<?php endif; ?>
				<?php endforeach; ?>
			</div>
		<?php endif; ?>


		<?php if( $footer_copyright ) : ?>
		<div class="footer__copyright">
			<?php echo '&copy; '.date('Y'); ?><?php echo ' - '.$footer_copyright; ?>
		</div>
		<?php endif; ?>
	</div>
</footer>
