<?php
	$collections_title = $this->themeSetting('home_itemsets_title');
	$itemsets_label = $this->themeSetting( 'home_itemsets_label');
	$itemsets_url_selection = ($this->themeSetting('home_itemsets_url')) ?: 1;
?>
<section class="collections">
	<div class="collections__wrap wrap wrap--smd">
		<h2 class="collections__title"><?php echo ($collections_title) ? $collections_title : $translate('Collections') ; ?></h2>
		<div class="collection__items">
			<?php

			if( $this->themeSetting( 'home_itemsets_selection') ):


				$collections_to_show = array();
				$collections_to_show = explode( ',',$this->themeSetting( 'home_itemsets_selection') );

				/* Uniquement pour afficher des collections associées au site - si aucun résultat vérifier que des collections sont associées au site */
				/* Filtre à remettre en service quand les collections auront été associées au site */
				$collections = $this->api()->search('item_sets', [
							'site_id' => $site->id(),
							'id' => $collections_to_show,
							'sort_by' => 'title',
							'sort_order' => 'asc',
						])->getContent();

				if ($collections) :

					foreach ($collections as $collection):

						$collection_heading = $collection->displayTitle();
						$collection_url = $collection->url();

						?>
						
							<div class="collection__item">
								<a href="<?php echo $collection_url; ?>">
									<div class="collection__thumbnail">
										<?php
											if( $this->thumbnail($collection, 'medium') ):
										?>
											<?php echo $this->thumbnail($collection, 'medium'); ?>
										<?php elseif ( $this->themeSetting( 'itemsets_thumbnail' ) ) : ?>                                     
											<img src="<?php echo $this->themeSettingAssetUrl('itemsets_thumbnail'); ?>" alt="" /> 
										<?php
											endif;
										?>
									</div>
									<h3 class="collection__title"><?php echo $collection_heading; ?></h3>
								</a>
							</div>
						<?php

					endforeach;

				endif;

			else:
				// Récupération des collections de 1er niveau
				$root_itemSetsTree = $this->itemSetsTree()->getItemSetsTree( 1 );

				foreach ($root_itemSetsTree as $root_collection):
					$root_itemSet = $root_collection['itemSet'];
					?>
					
					<div class="collection__item">
						<a href="<?php echo $root_itemSet->url(); ?>">
							<div class="collection__thumbnail">
								<?php
									if( $this->thumbnail($root_itemSet, 'medium') ):
								?>
									<?php echo $this->thumbnail($root_itemSet, 'medium'); ?>
								<?php elseif ( $this->themeSetting( 'itemsets_thumbnail' ) ) : ?>
									<img src="<?php echo $this->themeSettingAssetUrl('itemsets_thumbnail'); ?>" alt="" />
								<?php
									endif;
								?>
							</div>

							<h3 class="collection__title"><?php echo $root_itemSet->displayTitle(); ?></h3>
						</a>
					</div>
					
				<?php
				endforeach;

			endif;
			?>
		</div>
		<?php
			if($itemsets_label && ($itemsets_url_selection != 1) ):
				$itemsets_url = '';
				if($itemsets_url_selection == 2): 
					$itemsets_url = '/item-sets-tree';
				elseif($itemsets_url_selection == 3): 
					$itemsets_url = '/item-set';
				endif;
		?>
			<div class="button__container">
				<a href="<?php echo $site->url().$itemsets_url; ?>" class="button"><?php echo $itemsets_label; ?></a>
			</div>
		<?php endif; ?>
	</div>
</section>